# Generated by Django 5.0.3 on 2024-03-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_persons', models.IntegerField()),
                ('date', models.DateField()),
                ('duration_type', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in selected duration type')),
            ],
        ),
    ]
